<a href="https://colab.research.google.com/github/FaiazS/Movie_Review_Sentiment_Analysis/blob/main/MovieReviewSentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Without Embedding Layer

In [3]:
import tensorflow as tf

from tensorflow.keras import models, layers

import numpy as np

In [5]:
#Loading the data

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)

In [7]:
#Padding(One of the many types of Preparing/Pre-processing the Data)the data(Pre-proccesing the data).

#As IMDB reviews have different lengths, but Dense expects fixed number of neurons, and thus via Padding we are ensuring that every input
#is exactly 200 words

from tensorflow.keras.preprocessing.sequence import pad_sequences

x_train = pad_sequences(x_train, maxlen = 200)
x_test = pad_sequences(x_test, maxlen = 200)

In [8]:
#Building the Model

movie_review_model = models.Sequential([layers.Flatten(input_shape = (200,)),  #Converting 2D Sequence to 1D

                                        layers.Dense(128, activation = 'relu'),

                                        layers.Dense(64, activation = 'relu'),

                                        layers.Dense(1, activation = 'sigmoid')]) # Binary Classification thus the Activation Function
                                                                                  # for the Output Layer is Sigmoid,
                                                                                  # in case of Multi-Class Classification,
                                                                                  # the Activation Function for the Output Layer will be
                                                                                  # Softmax.

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
movie_review_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [11]:
movie_review_model.fit(x_train, y_train, epochs = 5, batch_size = 512)

Epoch 1/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.5039 - loss: 180.0608
Epoch 2/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5349 - loss: 57.6471
Epoch 3/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5538 - loss: 32.5152
Epoch 4/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5618 - loss: 20.4363
Epoch 5/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5635 - loss: 12.8121


In [13]:
#Testing/Evaluating Model

test_loss, test_accuracy = movie_review_model.evaluate(x_test, y_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4991 - loss: 13.1579


In [21]:
#Making Sentiment Prediction of Movie Review Post Training the Model

predicted_sentiment = movie_review_model.predict(x_test[0:1])

if(predicted_sentiment > 0.5):

  print("Positive")

else:

  print("Negative")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Positive


In [22]:
x_train

array([[   5,   25,  100, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [23]:
x_test

array([[   0,    0,    0, ...,   14,    6,  717],
       [1987,    2,   45, ...,  125,    4, 3077],
       [4468,  189,    4, ...,    9,   57,  975],
       ...,
       [   0,    0,    0, ...,   21,  846, 5518],
       [   0,    0,    0, ..., 2302,    7,  470],
       [   0,    0,    0, ...,   34, 2005, 2643]], dtype=int32)

In [24]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [25]:
y_test

array([0, 1, 1, ..., 0, 0, 0])

In [26]:
print(test_accuracy)

0.5015199780464172


With Embedding Layer

In [3]:
#Loading the required Libraries

import tensorflow as tf

from tensorflow.keras import models,layers

import numpy as np

In [53]:
#Loading the dataset

(x_train, y_train),(x_test, y_test) = tf.keras.datasets.imdb.load_data()

In [60]:
#Pre-proccessing the dataset via Padding

from tensorflow.keras.preprocessing.sequence import pad_sequences


x_train = pad_sequences(x_train, maxlen = 200)

x_test = pad_sequences(x_test, maxlen = 200)

In [61]:
#Building the model with additional Embedding Layer.

movie_review_model = models.Sequential (

                                        [layers.Embedding(input_dim = 10000, output_dim = 128, input_length =200),  #Converting word indices to vectors

                                        layers.Flatten(), #Flatten embeddings into a 1D Vector

                                        layers.Dense(128, activation = 'relu'),

                                        layers.Dense(64, activation = 'relu'),

                                        layers.Dense(1, activation = 'sigmoid')]

                                       )

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [62]:
movie_review_model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_7 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [63]:
#Compiling the Model with Hyper-Parameters

movie_review_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

In [69]:
#Training the Model

movie_review_model.fit(x_train, y_train, epochs = 5, batch_size = 512)

Epoch 1/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 19s 382ms/step - accuracy: 1.0000 - loss: 6.7483e-06
Epoch 2/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 20s 406ms/step - accuracy: 1.0000 - loss: 6.1291e-06
Epoch 3/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 18s 377ms/step - accuracy: 1.0000 - loss: 5.7734e-06
Epoch 4/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 18s 375ms/step - accuracy: 1.0000 - loss: 5.3607e-06
Epoch 5/5
49/49 ━━━━━━━━━━━━━━━━━━━━ 20s 371ms/step - accuracy: 1.0000 - loss: 5.0344e-06


In [71]:
#Evaluating the model

test_loss, test_accuracy = movie_review_model.evaluate(x_test, y_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.8601 - loss: 0.7707


In [78]:
print(test_accuracy)

0.8601599931716919
